name = "dragonaere-website"
compatibility_date = "2024-02-08"

[build]
command = "pnpm build"

[site]
bucket = "./dist"

[env.development]
name = "dragonaere-website-dev"
vars = { ENVIRONMENT = "development" }

[env.production]
name = "dragonaere-website"
routes = [
  { pattern = "dragonaere.net/*", zone_name = "dragonaere.net" }
]

[dev]
port = 8788