name = "dragonaere-website"
type = "javascript"
compatibility_date = "2024-02-08"

# Configure Static Site serving from /dist
[site]
bucket = "./dist"
entry-point = "functions/index.js"

[build]
command = "pnpm build"
watch_dir = "src"

[env.development]
name = "dragonaere-website-dev"
workers_dev = true
[env.development.vars]
ENVIRONMENT = "development"
ASSETS_URL = "http://127.0.0.1:5173"

[env.production]
name = "dragonaere-website"
workers_dev = false
routes = [
  { pattern = "dragonaere.net/*", zone_name = "dragonaere.net" }
]

[dev]
port = 8787
local_protocol = "http"
ip = "127.0.0.1"